[Feature] Hide category
actualbudget/actual pull request #1060
Opened 2023-05-25 13:40 UTC by Miodec

- Added the ability to hide category groups.
 - Added a menu to the budget header which for now just has one option: toggle visibility of hidden categories
<img width="314" alt="image" src="https://github.com/actualbudget/actual/assets/13181393/eeb9efe2-30fd-4acd-8751-149b5d2b7d2e">
<img width="245" alt="image" src="https://github.com/actualbudget/actual/assets/13181393/81e865e5-f9fd-4b1a-ab16-aabcfaa9b439">
<img width="313" alt="image" src="https://github.com/actualbudget/actual/assets/13181393/223c96e6-62fb-4cd8-a7c5-7ef28efe8ab6">

2023-05-25 20:56 UTC, MatissJanis commented
:wave: Very cool!

Personally I've been using a "hidden categories" group where I placed my unused categories. But that's more of a workaround than a proper solution.. your solution is definitely better.

Before I do a proper code review - two bugs/issues spotted:

1. if you hide all the categories within a group - the group stays visible, but it has no categories; would it make sense to hive the group too then? I think that makes sense
2. the "toggle hidden categories" option is not persisted - refreshing the page hides all the categories; can we persist it to user prefs?

2023-05-25 21:25 UTC, Miodec commented
> 👋 Very cool!
> 
> Personally I've been using a "hidden categories" group where I placed my unused categories. But that's more of a workaround than a proper solution.. your solution is definitely better.
> 
> Before I do a proper code review - two bugs/issues spotted:
> 
> 1. if you hide all the categories within a group - the group stays visible, but it has no categories; would it make sense to hive the group too then? I think that makes sense
> 2. the "toggle hidden categories" option is not persisted - refreshing the page hides all the categories; can we persist it to user prefs?

1. Oh yeah i forgot to point that out - i had a thought that the user might want to still see the group even if every category was hidden in case they wanted to add another category to that group. And also it could be a bit confusing if the category group dissapears, and the user might end up creating a copy? Just something to consider. Let me know, I can make it so the empty groups will not be shown.
2. Sure thing, could you point me to a component that already uses user prefs? Still learning the structure.

2023-05-25 23:23 UTC, j-f1 commented
> Sure thing, could you point me to a component that already uses user prefs? Still learning the structure.

The sidebar could be a good example of this since it preserves the pinned/floating state.

2023-05-26 14:32 UTC, shall0pass commented
I'm loving this.  A couple of follow up items when this gets merged.
1. The set budget options to "Last months budget" and "3 month average" should probably only apply to visible categories.
2. Goal templates should probably only apply to visible categories.

It would be easy to lose money into a hidden category and not realize it if they're auto filled with those types of shortcuts.

2023-05-26 15:43 UTC, youngcw commented
I like this.  Would it be doable to modify the nynab importer to automatically set the ynab hidden categories as hidden for actual?  I checked a ynab export and the hidden categories are labeled as such.

2023-05-26 18:32 UTC, Miodec commented
Storing state in user prefs.
Added group hiding which is separate from category hiding.

Should be fully ready for review.

2023-05-26 19:28 UTC, MatissJanis requested changes
Sweet!

A few small comments, but apart from that LGTM!

2023-05-26 19:28 UTC, MatissJanis commented on packages/desktop-client/src/components/budget/misc.js
> +                { name: 'toggleHide', text: category.hidden ? 'Show' : 'Hide' },
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏
```suggestion
                { name: 'toggleVisibility', text: category.hidden ? 'Show' : 'Hide' },
```

2023-05-26 19:28 UTC, MatissJanis commented on packages/desktop-client/src/components/budget/misc.js
> +                      name: 'toggleHidden',
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏
```suggestion
                      name: 'toggleVisibility',
```

2023-05-26 19:28 UTC, MatissJanis commented on packages/desktop-client/src/components/budget/misc.js
> +          // }
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏can be removed

2023-05-27 09:37 UTC, Miodec commented
Just trying to figure out if its possible to add automatic hiding inside the ynab5 importer.

2023-05-27 13:04 UTC, Miodec commented on packages/loot-core/migrations/1685123304382_add_category_groups_hidden.sql
> +ALTER TABLE category_groups ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT 0;
Done

2023-05-27 13:40 UTC, j-f1 approved these changes
Looks good to me, thank you!

2023-05-27 14:15 UTC, MatissJanis approved these changes
Amazing

2023-05-27 14:15 UTC, merged

2023-05-28 08:51 UTC, Kidglove57 commented
Loving the hidden categories feature. Working really well for me.

Thank you all for your hard work!