Add a new filter method that filters for transfer transactions
actualbudget/actual pull request #1181
Opened 2023-06-24 19:18 UTC by sriranganathan

- Add new field to the views to denote whether a transaction is transfer
- Implement new filter method that uses the above field
- Fixes #901

2023-06-25 00:33 UTC, j-f1 requested changes
Thank you for opening this PR! One big comment and one small one:

2023-06-25 00:33 UTC, j-f1 commented on packages/loot-core/migrations/1687644512504_add_is_transfer.sql
Would it be possible to define this on the view instead? Or check it in JS somehow? Since this is able to be derived from the payee I don’t think we should be storing it in the database.

2023-06-25 00:33 UTC, j-f1 commented on packages/loot-core/src/shared/rules.ts
> +      return 'Transfer';
Since all of the other field names are lower case, this one should be too:

```suggestion
      return 'transfer';
```

2023-07-18 19:43 UTC, MatissJanis commented
👋 Just checking in if you are planing to pick this up again @sriranganathan ?

2023-07-26 19:01 UTC, MatissJanis commented
👋 I'll close this off for now due to inactivity and the conflicts.

But please feel free to re-open (or open a new PR) if you resume working on this.

2023-07-26 19:01 UTC, closed without merging