Further reduce bundle size by code splitting out pages that are only used on desktop/mobile
actualbudget/actual pull request #1240
Opened 2023-06-30 22:14 UTC by j-f1

Since people on desktops generally won’t be using the mobile page components, and vice versa, I’ve updated the main router to dynamically load in which ever one is necessary. Since all components are bundled together in one file per size class, the latency when switching routes is ~4ms. This should significantly decrease the bundle size on mobile, which is important since mobile devices tend to have lower specs.

2023-07-01 16:17 UTC, MatissJanis reviewed
Overall LGTM. Just the `console.log` I think we should clean up.

2023-07-01 16:17 UTC, MatissJanis commented on packages/desktop-client/src/components/schedules/index.js
> +  console.log(`<Schedules> mounted at ${new Date().toISOString()}`);
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❓ question:** ‏should this be removed?

2023-07-01 16:17 UTC, MatissJanis commented on packages/desktop-client/src/components/budget/index.js
> +  console.log(`<BudgetWrapper> mounted at ${new Date().toISOString()}`);
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❓ question:** ‏should this be removed too?

2023-07-01 16:17 UTC, MatissJanis commented on packages/desktop-client/src/components/responsive/index.tsx
> +  );
also the console.logs in this file

2023-07-06 07:41 UTC, MatissJanis approved these changes

2023-07-19 07:38 UTC, MatissJanis approved these changes

2023-07-19 07:40 UTC, MatissJanis requested changes
Actually: small bug.

1. Open the mobile version
2. Open an account
3. Click "back" button in the app
4. The app crashes

```
TypeError: Cannot read properties of undefined (reading 'id')
```

2023-07-19 16:32 UTC, j-f1 commented
Fixed!

2023-07-19 16:40 UTC, MatissJanis approved these changes

2023-07-19 21:47 UTC, merged