Bugfix row render
actualbudget/actual pull request #1402
Opened 2023-07-27 21:45 UTC by biohzrddd

Fixed bug where all Account Transaction rows would be re-rendered on hover of a single Transaction row.

Watch the logged call count in the below movies. Before it goes up by 20+ (however many transactions are loaded) every time the mouse moves one row, after it goes up by 2 (the one being left and the one entered).

Before:
[Screencast_from_07-27-2023_090817_PM.webm](https://github.com/actualbudget/actual/assets/10577752/94ab0d52-ebee-4d16-ab1c-93061483d344)

After:
[Screencast_from_07-27-2023_103038_PM.webm](https://github.com/actualbudget/actual/assets/10577752/5741dca2-0f29-4e11-a91e-4d88dcb19cc6)

Note: there is still an existing re-render bug where selecting one row re-renders all other rows unnecessarily.

2023-07-28 01:09 UTC, j-f1 reviewed
I think I figured out why it is set up the way it is: on `master`, hovering over a row, then scrolling it out of view and back, will have it come back still highlighted. If you do that on this branch no rows will appear highlighted.

2023-07-28 07:59 UTC, biohzrddd commented
> I think I figured out why it is set up the way it is: on `master`, hovering over a row, then scrolling it out of view and back, will have it come back still highlighted. If you do that on this branch no rows will appear highlighted.

Must be browser-dependent? Not seeing on Firefox 115.0.2 on either master or this PR. Where are you saying you see that issue?

2023-07-28 08:00 UTC, biohzrddd commented
Also, seeing as how we're not even using the hover for anything but changing styles, this may as well be in-line CSS just like every other component. I'll update to use that, which will remove the unnecessary code.

2023-08-03 21:04 UTC, joel-jeremy requested changes

2023-08-03 21:04 UTC, joel-jeremy commented on packages/desktop-client/src/components/transactions/TransactionsTable.js
> +      onMouseEnter={() => !isNew && setHovered(true)}
Maybe we can start moving to pointer events?
```suggestion
      onPointerEnter={() => !isNew && setHovered(true)}
```

2023-08-03 21:04 UTC, joel-jeremy commented on packages/desktop-client/src/components/transactions/TransactionsTable.js
> +      onMouseLeave={() => !isNew && setHovered(false)}
Maybe we can start moving to pointer events?
```suggestion
      onPointerLeave={() => !isNew && setHovered(false)}
```

2023-08-11 21:19 UTC, joel-jeremy approved these changes

2023-08-13 05:16 UTC, merged

2023-08-16 19:43 UTC, MatissJanis commented
👋 There's a small regression introduced with this PR. The transaction selection checkbox is no longer visible when hovering on the table rows.

Could you take a look @biohzrddd ?