TypeScript migration (partial).
actualbudget/actual pull request #1671
Opened 2023-09-07 23:25 UTC by doggan

Working through some of the TypeScript migrations/hardening when running `yarn tsc --strict`.

`Found 3531 errors in 249 files. -> Found 3500 errors in 240 files.`

Related: https://github.com/actualbudget/actual/issues/1483

2023-09-08 03:33 UTC, doggan commented on packages/loot-core/src/shared/transactions.ts
>      }
Making `last` into a typed generic in `util.ts` bubbled up type issues to `transactions.ts`. This is the only location in the codebase using `last`, so it seemed most practical to just remove it.

2023-09-08 07:08 UTC, MatissJanis requested changes
Exciting to see all these TS improvements. I hope someday we will be fully TS compatible + strict :)

2023-09-08 07:08 UTC, MatissJanis commented on packages/desktop-client/src/components/manager/ConfigServer.tsx
> +    await setServerUrl('');
<!-- Warning represent user-facing problems. If possible, it's great to follow this kind of comment with a suggestion.  -->
**🔨 warning:** ‏we need to keep `null` here.

https://github.com/actualbudget/actual/blob/a8a0f777e2369a9f74becabab9f1eb96d50cba16/packages/loot-core/src/server/main.ts#L1775

2023-09-08 07:08 UTC, MatissJanis commented on packages/desktop-client/src/components/manager/ConfigServer.tsx
> +    await setServerUrl('');
Same here

2023-09-08 07:08 UTC, MatissJanis commented on packages/desktop-client/src/components/sidebar/ItemContent.tsx
> +  return onClick || !to ? (
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**💭 thought:** ‏I don't think we need this change.

2023-09-08 07:08 UTC, MatissJanis commented on packages/desktop-client/src/components/sidebar/ItemContent.tsx
> +  onClick?: MouseEventHandler<HTMLDivElement>;
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❓ question:** ‏is it that there can be either `to` or `onClick`? But not both at the same time? If so - we could solve it by changing the types slightly.

(very poor naming chosen here intentionally as this is just an example)

```
type BaseProps = { style: CSSProperties };
type ItemContentProps = AProps | BProps;

type AProps = BaseProps & { to: string };
type BProps = BaseProps & { onClick: () => void }; 
```

2023-09-24 23:43 UTC, doggan commented
Thanks for the feedback. Going to close this PR for now since it is stale and some of the changes have already been addressed in other merged PRs.

2023-09-24 23:43 UTC, closed without merging