Enhance Y-Axis Scaling on Net Worth Graph
actualbudget/actual pull request #1709
Opened 2023-09-18 00:04 UTC by Crazypkr1099

2023-09-18 00:16 UTC, Crazypkr1099 commented
The enhancement adds for scaling that makes sense based on your Net-Worth. Currently, if your Net-Worth is high but your income up/down is low, its very hard to see on the chart. I added code to specify what your y min-max should be so it's easy to see the increase/decrease.

Below is an examples:

**BEFORE ENHANCEMENT**
![Networth-before-July-Sept](https://github.com/actualbudget/actual/assets/11566471/c16d903f-b39b-48e2-a268-cd7a99587a1f)

**AFTER ENHANCEMENT**
![Networth-after-July-Sept](https://github.com/actualbudget/actual/assets/11566471/f3f0f498-2dc9-4d21-8e9e-2a6dda7d6511)

**ANOTHER EXAMPLE (LEFT = Enhanced)**
![Networth-after-may-Sept](https://github.com/actualbudget/actual/assets/11566471/be24676f-c4e2-4940-bebc-bfe7e08e5d66)

2023-09-18 19:46 UTC, MatissJanis requested changes
Really cool addition! This makes the net-worth graph so much more usable.

Thanks!

2023-09-18 19:46 UTC, MatissJanis commented on packages/desktop-client/src/components/reports/graphs/net-worth-spreadsheet.tsx
> +    highestNetWorth: highestNetWorth,
<!-- Nitpicks are small, trivial, but necessary changes. Distinguishing nitpick comments significantly helps direct the reader's attention to comments requiring more involvement.  -->
**🥜 nitpick:** ‏
```suggestion
    lowestNetWorth,
    highestNetWorth,
```

2023-09-18 19:46 UTC, MatissJanis commented on packages/desktop-client/src/components/reports/graphs/net-worth-spreadsheet.tsx
> +      }
<!-- Nitpicks are small, trivial, but necessary changes. Distinguishing nitpick comments significantly helps direct the reader's attention to comments requiring more involvement.  -->
**🥜 nitpick:** ‏strict null checks
```suggestion
      if (item.y < lowestNetWorth || lowestNetWorth === null) {
        lowestNetWorth = item.y;
      }
      if (item.y > highestNetWorth || highestNetWorth === null) {
        highestNetWorth = item.y;
      }
```

2023-09-18 19:46 UTC, MatissJanis commented on packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
> +            domain={domainMinMax}
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏ideally we use the same variable name here. Aliasing and renaming things down multiple layers of code leads to difficult to read code.

2023-09-18 19:46 UTC, MatissJanis commented on packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
> +  domainMinMax;
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏could you please add a type for the new prop?

2023-09-18 19:46 UTC, MatissJanis commented on packages/desktop-client/src/components/reports/NetWorth.js
> +              data.highestNetWorth + data.highestNetWorth * 0.01,
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**💬 suggestion:** ‏could be simplified
```suggestion
              data.lowestNetWorth * 0.99,
              data.highestNetWorth * 1.01,
```

2023-09-19 16:13 UTC, MatissJanis commented on packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
> +  domain: domainProp;
<!-- Warning represent user-facing problems. If possible, it's great to follow this kind of comment with a suggestion.  -->
**🔨 warning:** ‏`[number, number]` won't be correct here. You could either do `{ y?: [number, number]; x?: [number, number] }` or..

```suggestion
  domain: React.ComponentProps<typeof Chart>["domain"];
```

2023-09-19 17:40 UTC, MatissJanis approved these changes

2023-09-19 17:40 UTC, merged