Darkmode: fix theming on budget table
actualbudget/actual pull request #1795
Opened 2023-10-14 17:35 UTC by youngcw

Much of the budget table wasn't themed, but had hard coded colors.  This moves over to the theme values.

2023-10-14 17:36 UTC, youngcw commented
@carkom Here is some help

2023-10-14 18:25 UTC, carkom commented
This looks pretty good. Thanks for your help. Just a couple nits below.

2023-10-14 18:29 UTC, carkom requested changes

2023-10-14 18:29 UTC, carkom commented on packages/desktop-client/src/components/budget/BudgetTotals.js
> +        backgroundColor: theme.tableHeaderBackground,
The light mode doesn't use a different tableheaderbackground here. We should follow this.
```suggestion
        backgroundColor: theme.tableBackground,
```

2023-10-15 15:00 UTC, carkom approved these changes
LGTM!

2023-10-16 14:13 UTC, joel-jeremy approved these changes

2023-10-16 14:13 UTC, merged