Convert FiltersMenu to Typescript
actualbudget/actual pull request #2231
Opened 2024-01-14 22:07 UTC by carkom

Split out all the elements into separate files - working to get rid of mega-files in the code base. Updated all those files to Typescript.

2024-01-25 17:18 UTC, twk3 commented
@carkom what do you think about using a `utils.ts` to hold `subfieldFromFilter`, `subfieldToOptions` and `updateFilterReducer`?

2024-01-25 19:01 UTC, twk3 requested changes

2024-01-27 16:45 UTC, carkom commented
> @carkom what do you think about using a `utils.ts` to hold `subfieldFromFilter`, `subfieldToOptions` and `updateFilterReducer`?

I think we are focused on avoiding combined files in this project.

2024-01-29 18:49 UTC, twk3 approved these changes
The new changes look good. Thanks!

2024-02-02 20:10 UTC, merged