Fix OFX import with non-unique FITID
actualbudget/actual pull request #2646
Opened 2024-04-20 14:43 UTC by Wizmaster

Fix #608

When importing, only merge transaction found with same imported_id if the imported_payee and amount also match, and if a single transaction was found. Else let the fuzzy matching try to find a transaction match.

In the comment https://github.com/actualbudget/actual/issues/608#issuecomment-2067322290 I thought using the date to match the transaction but decided against it, the user could change the date to their liking and matching on it would becomes unreliable.

Testing with the OFX files provided in #608 was conclusive. Only 3 transactions were mistakenly merged:
- 1 due to issue #2420, the dates where close enough and the amounts the same
- 2 due to fitid, amounts and payee info being the same (the issue arose because the payee used were "Generic Transaction #xx" with xx being the fitid, something I believe unlikely with real data)

Testing with my own data was also ok.

2024-04-20 17:50 UTC, MatissJanis requested changes
I do not think we should apply this change.

Firstly, we cannot rely on `imported_payee` field to be immutable. Some banks include dates and other nonsense in this field. So it is possible for a transaction to change its `imported_payee` during its lifecycle.

Furthermore, according to the OFX spec - FITID are **unique** transaction IDs. If they are not unique - the issue should be patched at the source rather than trying to work around it in Actual.

2024-04-20 18:49 UTC, Wizmaster commented
> I do not think we should apply this change.
> 
> Firstly, we cannot rely on `imported_payee` field to be immutable. Some banks include dates and other nonsense in this field. So it is possible for a transaction to change its `imported_payee` during its lifecycle.
> 
> Furthermore, according to the OFX spec - FITID are **unique** transaction IDs. If they are not unique - the issue should be patched at the source rather than trying to work around it in Actual.

Agreed, but patching at the source means getting any bank out there which does not implement correctly OFX standard to patch its system, something more easily said than done. I think Actual should avoid having a destructive behaviour (loss of transaction due to merge of another one).

I understand `imported_payee` could also change. In the proposed PR it would then not match and the fuzzy matching would then try to identify the matching transaction. In case it failed too, it would result in a duplicated transaction, something I think is more desirable should it happens than a lost transaction.

I can remove the test on `imported_payee` and only keep matching the `amount`, but I feel it's better if it could stay here.

2024-04-20 19:15 UTC, MatissJanis commented
My recommendation for your use case is to export a specific date-range from the bank. And then import that with the dedupe logic turned off (there is a checkbox in the import modal).

Alternatively to write a script that patches your FITID field in the local OFX file prior to importing in Actual.

2024-04-21 11:14 UTC, Wizmaster commented
Thanks for the recommandations!

I'll think I'll stick with running a fork then. I still have a few weeks left on my nYNAB sub to continue double-running the app and look for any weird behaviour or lost transactions.

2024-04-21 11:14 UTC, closed without merging