Update regex for `looselyParseAmount` for 5-9 decimal places
actualbudget/actual pull request #2799
Opened 2024-05-25 16:55 UTC by sreetamdas

2024-05-25 17:22 UTC, youngcw approved these changes
Thanks.  Ill wait until after the merge freeze to merge this in.

2024-05-29 02:28 UTC, psybers requested changes

2024-05-29 02:28 UTC, psybers commented on packages/loot-core/src/shared/util.test.ts
>      expect(looselyParseAmount('3.45')).toBe(3.45);
There is a comment a few lines above this that should be updated for the new parsing.

2024-05-30 16:57 UTC, psybers approved these changes

2024-06-03 14:39 UTC, youngcw commented
Can you look into why VRT is failing?  Double check that you are fully up to date with master, but it could still be an external problem

2024-06-03 14:51 UTC, youngcw approved these changes

2024-06-03 14:52 UTC, merged