Add computed padding for handling clipped large Net worth amounts
actualbudget/actual pull request #2818
Opened 2024-06-02 13:50 UTC by sreetamdas

In the Net Worth report, amounts over ~6 digits get clipped because of [zero margin added](https://github.com/actualbudget/actual/blob/08aff05a06f4bca4344f939324080e1fa6511b62/packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx#L124).

```jsx
<AreaChart
  width={width}
  height={height}
  data={graphData.data}
  margin={{ top: 0, right: 0, left: 0, bottom: 0 }}
>
```

<details><summary>Before</summary>
<p>

<img width="1440" alt="image" src="https://github.com/actualbudget/actual/assets/11270438/ad0c44bb-6b52-4b10-adec-08041a03be4d">

</p>
</details> 

---

Fix by adding a left padding that takes into account the length of the net worth amount (so it can handle even bigger amounts, which is common in currencies like INR, VND, etc.)

```jsx
/**
 * Add left padding for Y-axis for when large amounts get clipped
 */
function computePadding(netWorthData: Array<{ y: number }>) {
  /**
   * Convert to string notation, get longest string length
   */
  const maxLength = Math.max(
    ...netWorthData.map(({ y }) => {
      return Math.round(y).toLocaleString().length;
    }),
  );

  if (maxLength <= 5) {
    // No additional left padding is required for upto 5 characters
    return 0;
  }

  return (maxLength - 5) * 5;
}
```

<details><summary>After</summary>
<p>

<img width="1440" alt="image" src="https://github.com/actualbudget/actual/assets/11270438/0e469b1a-0aa4-449d-a04b-091a1c4f7e52">

</p>
</details>

2024-06-15 00:59 UTC, psybers requested changes

2024-06-15 00:59 UTC, psybers commented on packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
> +  return (maxLength - 5) * 5;
```suggestion
  // No additional left padding is required for upto 5 characters
  return Math.max(0, (maxLength - 5) * 5);
```

2024-06-15 03:30 UTC, sreetamdas commented on packages/desktop-client/src/components/reports/graphs/NetWorthGraph.tsx
> +  return (maxLength - 5) * 5;
This is better indeed, thanks!

2024-06-15 19:22 UTC, psybers approved these changes

2024-06-15 19:23 UTC, psybers commented
You will need to update the VRT tests.

2024-06-19 04:40 UTC, psybers requested changes

2024-06-19 04:40 UTC, psybers commented on packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
It looks like there might be a bit of a problem.  The net worth graph is now slightly cut off on the left side.

2024-06-20 12:42 UTC, sreetamdas commented on packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
Sorry about that @psybers, I've fixed this and run VRT again and updated the snapshots. Thanks!

2024-06-20 14:03 UTC, psybers requested changes

2024-06-23 12:54 UTC, sreetamdas commented on packages/desktop-client/e2e/reports.test.js-snapshots/Reports-loads-net-worth-and-cash-flow-reports-1-chromium-linux.png
Sorry, should be fixed now!

2024-06-23 20:30 UTC, psybers approved these changes

2024-07-04 16:02 UTC, youngcw commented
Im guessing that merging master will fix these conflicts.  Can you look into that?

2024-07-08 15:13 UTC, youngcw approved these changes
Thanks!

2024-07-08 15:13 UTC, merged