More React Aria Button
actualbudget/actual pull request #2984
Opened 2024-07-05 05:43 UTC by joel-jeremy

2024-07-17 19:34 UTC, MatissJanis requested changes

2024-07-17 19:34 UTC, MatissJanis commented on packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-4-chromium-linux.png
bug: the transfer icon color has changed. It's basically invisible now.

2024-07-17 19:34 UTC, MatissJanis commented on packages/desktop-client/e2e/budget.test.js-snapshots/Budget-renders-the-summary-information-available-funds-overspent-budgeted-and-for-next-month-1-chromium-linux.png
bug: the notes icons are always visible now. Should only be visible on hover.

2024-07-18 17:30 UTC, MatissJanis commented
Compared to `edge` - the notes button hover is still behaving quite differently than before. The new behaviour makes notes much less discoverable.

2024-07-26 00:52 UTC, matt-fidd commented on packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-5-chromium-linux.png
The hover effect on the mealballs (?) menu in these screenshots is new. Is there an unintended focus change on load that only appears on VRT? Seems to work as expected in the demo deployment so I assume it's a symptom of the VRT env.

2024-07-29 20:52 UTC, MikesGlitch approved these changes
I think this looks great. I've given it a runthrough and haven't seen anything out of place.

2024-08-03 16:06 UTC, MatissJanis approved these changes

2024-08-06 02:08 UTC, matt-fidd approved these changes

2024-08-06 02:44 UTC, merged