[React Aria Button] Reports page buttons
actualbudget/actual pull request #3159
Opened 2024-07-29 18:33 UTC by joel-jeremy

2024-08-09 00:35 UTC, matt-fidd commented
@joel-jeremy another change must have introduced some conflicts, not sure if you're aware

2024-08-12 20:22 UTC, MatissJanis approved these changes

2024-08-12 20:53 UTC, merged

2024-08-14 01:16 UTC, carkom requested changes

2024-08-14 01:16 UTC, carkom commented on packages/desktop-client/src/components/reports/ModeButton.tsx
> +          ...style,
This is the wrong place. Needs to match previous file. It's causing a regression in spending report.