🐛(titlebar) update server status on sync
actualbudget/actual pull request #3164
Opened 2024-07-30 23:20 UTC by xZToxicZx

fixes #3128

2024-08-07 01:04 UTC, psybers requested changes

2024-08-07 01:04 UTC, psybers commented on packages/desktop-client/src/components/LoggedInUser.tsx
When I tested it, I wound up in this state:

<img width="204" alt="image" src="https://github.com/user-attachments/assets/940c8460-50b0-413b-ba34-3572c5858cd8">

And then after a bit, somehow my server crashed so while Wifi was back it couldn't reach it and it wound up in this state:

<img width="187" alt="image" src="https://github.com/user-attachments/assets/96d25596-a777-4af9-b9b6-35cebcc37e84">

So I don't think this actually fixes the issue, unfortunately.  At least not entirely.

2024-08-07 03:03 UTC, psybers commented
What about sharing the sync state, which is set in the `SyncButton`?  We could lift that state up to the parent `Titlebar` and then share it with both children (`SyncButton` and `LoggedInUser`).  Something like this maybe?

```diff
diff --git a/packages/desktop-client/src/components/LoggedInUser.tsx b/packages/desktop-client/src/components/LoggedInUser.tsx
index 0df0d616..06a6d5df 100644
--- a/packages/desktop-client/src/components/LoggedInUser.tsx
+++ b/packages/desktop-client/src/components/LoggedInUser.tsx
@@ -1,8 +1,5 @@
 // @ts-strict-ignore
-import React, { useState, useEffect, useRef } from 'react';
-import { useSelector } from 'react-redux';
-
-import { type State } from 'loot-core/src/client/state-types';
+import React, { useState, useEffect, useRef, useMemo } from 'react';
 
 import { useActions } from '../hooks/useActions';
 import { theme, styles, type CSSProperties } from '../style';
@@ -16,15 +13,16 @@ import { useServerURL } from './ServerContext';
 
 type LoggedInUserProps = {
   hideIfNoServer?: boolean;
+  syncState: null | 'offline' | 'local' | 'disabled' | 'error';
   style?: CSSProperties;
   color?: string;
 };
 export function LoggedInUser({
   hideIfNoServer,
+  syncState,
   style,
   color,
 }: LoggedInUserProps) {
-  const userData = useSelector((state: State) => state.user.data);
   const { getUserData, signOut, closeBudget } = useActions();
   const [loading, setLoading] = useState(true);
   const [menuOpen, setMenuOpen] = useState(false);
@@ -62,17 +60,17 @@ export function LoggedInUser({
     }
   }
 
-  function serverMessage() {
+  const serverMessage = useMemo(() => {
     if (!serverUrl) {
       return 'No server';
     }
 
-    if (userData?.offline) {
+    if (syncState === 'offline') {
       return 'Server offline';
     }
 
     return 'Server online';
-  }
+  }, [serverUrl, syncState]);
 
   if (hideIfNoServer && !serverUrl) {
     return null;
@@ -101,7 +99,7 @@ export function LoggedInUser({
         onPress={() => setMenuOpen(true)}
         style={color && { color }}
       >
-        {serverMessage()}
+        {serverMessage}
       </Button>
 
       <Popover
@@ -113,7 +111,7 @@ export function LoggedInUser({
           onMenuSelect={onMenuSelect}
           items={[
             serverUrl &&
-              !userData?.offline && {
+              syncState === null && {
                 name: 'change-password',
                 text: 'Change password',
               },
diff --git a/packages/desktop-client/src/components/Titlebar.tsx b/packages/desktop-client/src/components/Titlebar.tsx
index 9c25bbd1..f1300196 100644
--- a/packages/desktop-client/src/components/Titlebar.tsx
+++ b/packages/desktop-client/src/components/Titlebar.tsx
@@ -1,4 +1,4 @@
-import React, { useState, useEffect } from 'react';
+import React, { useState, useEffect, type SetStateAction } from 'react';
 import { useHotkeys } from 'react-hotkeys-hook';
 import { Routes, Route, useLocation } from 'react-router-dom';
 
@@ -94,16 +94,22 @@ function PrivacyButton({ style }: PrivacyButtonProps) {
 
 type SyncButtonProps = {
   style?: CSSProperties;
+  syncState: string | null;
+  setSyncState: (
+    state: SetStateAction<null | 'offline' | 'local' | 'disabled' | 'error'>,
+  ) => void;
   isMobile?: boolean;
 };
-function SyncButton({ style, isMobile = false }: SyncButtonProps) {
+function SyncButton({
+  style,
+  syncState,
+  setSyncState,
+  isMobile = false,
+}: SyncButtonProps) {
   const [cloudFileId] = useLocalPref('cloudFileId');
   const { sync } = useActions();
 
   const [syncing, setSyncing] = useState(false);
-  const [syncState, setSyncState] = useState<
-    null | 'offline' | 'local' | 'disabled' | 'error'
-  >(null);
 
   useEffect(() => {
     const unlisten = listen('sync-event', ({ type, subtype, syncDisabled }) => {
@@ -261,6 +267,9 @@ export function Titlebar({ style }: TitlebarProps) {
   const { isNarrowWidth } = useResponsive();
   const serverURL = useServerURL();
   const [floatingSidebar] = useGlobalPref('floatingSidebar');
+  const [syncState, setSyncState] = useState<
+    null | 'offline' | 'local' | 'disabled' | 'error'
+  >(null);
 
   return isNarrowWidth ? null : (
     <View
@@ -331,8 +340,14 @@ export function Titlebar({ style }: TitlebarProps) {
         <ThemeSelector style={{ marginLeft: 10 }} />
       )}
       <PrivacyButton style={{ marginLeft: 10 }} />
-      {serverURL ? <SyncButton style={{ marginLeft: 10 }} /> : null}
-      <LoggedInUser style={{ marginLeft: 10 }} />
+      {serverURL ? (
+        <SyncButton
+          syncState={syncState}
+          setSyncState={setSyncState}
+          style={{ marginLeft: 10 }}
+        />
+      ) : null}
+      <LoggedInUser syncState={syncState} style={{ marginLeft: 10 }} />
     </View>
   );
 }
```

2024-08-10 10:06 UTC, closed without merging

2024-08-10 10:07 UTC, MikesGlitch commented
Closed in favor of https://github.com/actualbudget/actual/pull/3213

Thanks for the contribution!