feat(rules): templating actions
actualbudget/actual pull request #3305
Opened 2024-08-22 20:08 UTC by UnderKoen

Relates to #500  and #3378 

https://github.com/user-attachments/assets/809ee622-af8a-4151-9293-8ce4e9dbdb91

2024-08-23 14:51 UTC, youngcw commented
Could you put in some more examples of what is possible with this?  I see that you can pull in field values, can you pull in things like account balance?

2024-08-23 15:49 UTC, UnderKoen commented
You can currently only pull in information about the transaction. This is limited to anything what is currently possible with data available to rules. So not the name of the payee or name of the category. I saw an todo `// TODO: Add matches op support for payees, accounts, categories.` which woudl probaly also make this possible!

The main use case for this would currently be cleaning imported transactions. Or altering existing transactions.

Or changing the date of new income to the first of the month.
`{{floor (add (year date) (div (month date) 12))}}-{{add (mod (month date) 12) 1}}-1`

Is this now very verbose but we could add another helper for adding duration to dates.

The helpers I currently implemented are:
- `regex value regex replacement`
- `add num1 num2 ...`
- `sub num1 num2 ...`
- `div num1 num2 ...`
- `mul num1 num2 ...`
- `mod num1 num2 ...`
- `floor num`
- `ceil num`
- `round num`
- `abs num`
- `min num1 num2 ...`
- `max num1 num2 ...`
- `fixed num1 num2`
- `day date`
- `month date`
- `year date`
- `format date format`

Values available:
- today (date)
- account (id)
- amount (number)
- cleared (boolean)
- date (date)
- error (?)
- imported_id (id)
- imported_payee (string)
- is_child (boolean)
- is_parent (boolean)
- notes (string)
- parent_id (id)
- payee (id)
- reconciled (boolean)
- schedule (id)
- sort_order (number)
- starting_balance_flag (boolean)
- tombstone (boolean)
- transfer_id (id)

This list can be extended by adding more values at `rules.ts#569` like how `today` is added.

2024-08-24 16:56 UTC, youngcw commented
There probably needs to be a syntax check in the rule edit window since its so easy to have bad syntax with something like this.

Are these supposed to run when manually creating a transaction?  My testing doesn't seem to work in that case.  I think its working for file imports though.

Im worried that there could be some issues with how the csv import checks for duplicates if someone has a templated rule.  That will require more testing.

2024-08-26 06:55 UTC, UnderKoen commented
@youngcw 
> There probably needs to be a syntax check in the rule edit window since its so easy to have bad syntax with something like this.
Will add

> Are these supposed to run when manually creating a transaction? My testing doesn't seem to work in that case. I think its working for file imports though.
I just tested this and it has been working but not consistently, I think the rules are not always run?

> Maybe we should look at moving the rules inside of the check that the csv import does for duplication matching.
Seems smart, I wouldn't have a clue how to achieve this. Could this be fixxed in an separatem PR and making this feature expiremental?

2024-08-26 15:41 UTC, youngcw commented
Making this experimental would probably be good for now.

2024-08-26 15:42 UTC, youngcw commented
> * tombstone (boolean)

Can this be set? or is it just available to use?

2024-09-04 13:51 UTC, youngcw commented
> Out of scope of this PR I think but wouldn't this be best solved with field like `imported_payee`? Just have `imported_amount`, `imported_notes`, etc.

I don't think that will fix if the amount gets changed

2024-09-04 14:57 UTC, UnderKoen commented
> Im worried that there could be some issues with how the csv import checks for duplicates if someone has a templated rule. That will require more testing.

> edit: So the csv importer can't see the matching transaction if there is a big change (change the amount sign for example), but the rule gets run before the real deduplication goes. Maybe we should look at moving the rules inside of the check that the csv import does for duplication matching.

I don't think I understand what the intented behaviour is and how to check the behaviour?

2024-09-04 15:33 UTC, youngcw commented
> > Im worried that there could be some issues with how the csv import checks for duplicates if someone has a templated rule. That will require more testing.
> 
> > edit: So the csv importer can't see the matching transaction if there is a big change (change the amount sign for example), but the rule gets run before the real deduplication goes. Maybe we should look at moving the rules inside of the check that the csv import does for duplication matching.
> 
> I don't think I understand what the intented behaviour is and how to check the behaviour?

If you import a csv and then import the same csv again you should see that all the "new" transactions get matched with the existing transaction and shown to you in the import window to decide what to do.  So compare that to if you have a rule that modifies the amount using a template rule and there wont be a match even though its the same transaction and will get deduplicated after the rules run.

2024-09-04 15:45 UTC, UnderKoen commented
Does this not work with the exported CSV's? I have no rules active and use the demo file
![image](https://github.com/user-attachments/assets/0a1dcdab-0017-4d37-8763-19a3e8e6867c)

2024-09-09 17:13 UTC, Djurq commented
This would be awesome!

2024-09-10 17:30 UTC, youngcw commented
with the CSV?  Its not that the CSV import isn't working.  The CSV importer shows which transactions are new and which ones match an existing transaction.  If the rules change the amounts, for example, then  the matching doesn't work since the transaction has changed too much.

2024-09-10 17:41 UTC, UnderKoen commented
@youngcw How does this look, when I import an CSV I don't see anywhere that it matches even with no rules active. After importing with and without rules there are no duplicates.

2024-09-10 17:43 UTC, youngcw commented
Import the same csv twice and you will see extra lines in the import window the second time.  Those lines will show the matching

2024-09-10 17:49 UTC, UnderKoen commented
@youngcw I don't see any extra line?

![2024-09-10 19 46 chrome_HV526F7C2X](https://github.com/user-attachments/assets/84c76fd6-9cfd-4341-b38a-68868618d62f)
![2024-09-10 19 46 chrome_PVxZgABVCy](https://github.com/user-attachments/assets/4c8ff62b-50da-4f80-90d7-e0b105ebf3f8)

2024-09-10 17:57 UTC, youngcw commented
Hmm. Something must have broke.  Im not seeing it anymore either.

2024-09-10 17:59 UTC, youngcw commented
https://deploy-preview-3179.demo.actualbudget.org/  This is the deploy for v24.8.0.  It still works with the matching so you can see what it is supposed to be doing.

2024-09-10 18:04 UTC, youngcw commented
Its possible that this would work fine if the table wasn't messed up prior to this.

2024-09-10 18:15 UTC, UnderKoen commented
Ahha, thanks I really tough I was going crazy

2024-09-18 19:36 UTC, UnderKoen commented
@youngcw it seems that the templating rules work with the CSV import. Could you confirm?

2024-10-04 19:48 UTC, UnderKoen commented on packages/loot-core/src/server/accounts/rules.test.ts
> +      testHelper('{{regex notes "/[aeuio]/" ""}}', 'Srah Condition');
There is no global flag so it should only replace the first letter

2024-10-08 15:15 UTC, youngcw commented
Ill need to look more, but the csv matching logic seems to be working.  The only thing that is a little weird is that the line that shows the existing transaction that matches will show the after rules version and the line that shows the incoming version doesn't have rules applied, but they show as matching.  I guess that makes sense, but maybe we could do something to make it clear why they are different in the future.

2024-10-08 15:16 UTC, youngcw commented
Also, this will need a pretty thorough docs page since this gets complicated fast.

2024-10-08 16:12 UTC, matt-fidd requested changes
Thanks for this!

Just a quick couple of changes with how the settings toggle is presented

2024-10-08 16:12 UTC, matt-fidd commented on packages/desktop-client/src/components/settings/Experimental.tsx
> +            <FeatureToggle flag="actionTemplating">
```suggestion
            <FeatureToggle
              flag="actionTemplating"
              feedbackLink="https://github.com/actualbudget/actual/issues/3606"
            >
```

2024-10-08 16:12 UTC, matt-fidd commented
Opened tracking issue #3606 for experimental feedback

2024-10-08 16:39 UTC, matt-fidd approved these changes
Amazing, thank you for this! I'd like to get it merged in as is for now to release it into the hands of `edge` users and gather some feedback before the next release cycle.

2024-10-08 16:41 UTC, youngcw approved these changes

2024-10-08 16:43 UTC, merged