Translation: desktop-client/src/components/budget/BalanceWithCarryover.tsx
actualbudget/actual pull request #3352
Opened 2024-09-02 22:55 UTC by nmathey

Translation support for `desktop-client/src/components/budget/BalanceWithCarryover.tsx`

2024-09-03 01:55 UTC, psybers requested changes

2024-09-03 01:55 UTC, psybers commented on packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
>                    <span style={{ color: theme.noticeText }}>Fully funded</span>
Missed some text here.

2024-09-03 01:55 UTC, psybers commented on packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
> +                    {t('Overfunded')} ({format(differenceToGoal, 'financial')})
Here, I think the amount needs to be part of the translation string.  So something like this:

```suggestion
                    {t('Overfunded ({{amount}})', { amount: format(differenceToGoal, 'financial') })}
```

2024-09-03 03:15 UTC, nmathey commented on packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
>                    <span style={{ color: theme.noticeText }}>Fully funded</span>
oups :)

2024-09-03 03:15 UTC, psybers commented on packages/desktop-client/src/components/budget/BalanceWithCarryover.tsx
> +                    {t('Overfunded')} ({format(differenceToGoal, 'financial')})
Yes, or maybe in that language parens don't make sense.

2024-09-13 17:06 UTC, MatissJanis approved these changes
Thanks!

2024-09-13 17:07 UTC, merged