test: csv import e2e tests
actualbudget/actual pull request #3499
Opened 2024-09-24 20:10 UTC by UnderKoen

Readds #3467
The problem that caused #3474 was something to do with css precedent

2024-09-24 20:19 UTC, UnderKoen commented on packages/desktop-client/e2e/accounts.test.js
> +    });
This is checked visually by the screenshots

2024-09-24 20:20 UTC, UnderKoen commented on packages/desktop-client/e2e/page-models/close-account-modal.js
> +  }
As this is not done in the other methods I chose not todo this as it seems not to be the standart

2024-09-24 20:22 UTC, UnderKoen commented on packages/desktop-client/e2e/accounts.test.js
> +    });
The test checks whether the csv options get greyed out because that are matched with existing transactions

2024-09-25 20:39 UTC, MatissJanis requested changes
👋 I ran the tests 5x to check for flakiness. There is a bit of flakiness (2 failures out of 7x runs). Would you mind checking them to see if something could be improved?

Here's a sample flake: https://github.com/actualbudget/actual/actions/runs/11040670144/job/30669239338?pr=3499

(ignore the other tests also flaking - I'm working on getting them in top shape too)

2024-10-04 07:33 UTC, UnderKoen commented on packages/desktop-client/src/components/modals/CloseAccountModal.tsx
> +                      aria-label="Force close"
Unfortunatly, this didn't work. So I removed it completely and the flakiness seems gone now :D

2024-10-04 07:40 UTC, UnderKoen commented on bin/run-vrt
> +E2E_START_URL="${E2E_START_URL:-https://host.docker.internal:3001}"
```suggestion
E2E_START_URL="${E2E_START_URL:-https://localhost:3001}"
```

2024-10-04 17:57 UTC, MatissJanis approved these changes
Re-ran a couple of times and the tests are now stable! Thanks!

Would you mind fixing the conflict? I must have just introduced it when merging https://github.com/actualbudget/actual/pull/3552

2024-10-04 19:55 UTC, MatissJanis approved these changes

2024-10-08 22:27 UTC, matt-fidd commented on packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
Is there a reason these would have changed? Looks like we're missing "New Account" from the sidebar.

2024-10-09 06:50 UTC, UnderKoen commented on packages/desktop-client/e2e/accounts.test.js-snapshots/Accounts-closes-an-account-1-chromium-linux.png
It makes an new test file for each test now. It was unstable before, run order wasn't always the same, especially when the first try failed

2024-10-09 07:34 UTC, matt-fidd approved these changes

2024-10-09 07:35 UTC, merged