Marked files for translation
actualbudget/actual pull request #3752
Opened 2024-10-29 11:44 UTC by awaisalee

Marked files for translation:

- packages/desktop-client/src/components/LoggedInUser.tsx
- packages/desktop-client/src/components/sidebar/PrimaryButtons.tsx
- packages/desktop-client/src/components/transactions/TransactionsTable.jsx
- packages/desktop-client/src/components/UpdateNotification.tsx
- packages/loot-core/src/platform/server/fs/index.electron.ts
- packages/loot-core/src/platform/server/fs/index.web.ts
- packages/loot-core/src/platform/server/fs/shared.ts
- packages/loot-core/src/server/accounts/parse-file.ts
- packages/loot-core/src/server/accounts/qif2json.ts
- packages/loot-core/src/server/app.ts
- packages/loot-core/src/server/aql/exec.ts
- packages/loot-core/src/server/aql/schema-helpers.ts
- packages/loot-core/src/server/aql/schema/executors.ts

2024-11-06 20:19 UTC, MikesGlitch reviewed
This looks great! I've added some minor points about translating errors. Ideally we don't want to do that - those errors are for devs and for support - they shouldn't be shown to the user so shouldn't be translated. 

E2E tests are failing as well - if you need help let us know.

2024-11-06 20:19 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Export.tsx
> +      console.log(t('Export error code:'), response.error);
```suggestion
      console.log('Export error code:', response.error);
```

Shouldn't need to translate console logs

2024-11-06 20:19 UTC, MikesGlitch commented on packages/loot-core/src/platform/server/fs/index.electron.ts
> +    console.error(
No need to translate error logs

2024-11-06 20:19 UTC, MikesGlitch commented on packages/loot-core/src/platform/server/fs/index.web.ts
> +      throw new Error(t('File does not exist:') + ' ' + filepath);
Same here, these aren't shown to the user so no need to translate them. Ideally they'd be english so we can read them in English when people come for support

2024-11-06 20:19 UTC, MikesGlitch commented on packages/loot-core/src/platform/server/fs/index.web.ts
> +      throw new Error(t('File does not exist:') + ' ' + filepath);
Here too - I wont put a comment on all of them but it would be ideal to remove them all 👍

2024-11-06 20:19 UTC, MikesGlitch commented on packages/loot-core/src/platform/server/fs/shared.ts
> +    throw new Error(t('Document directory is not set'));
No need to translate thrown errors (check rest of this file for the same issue)

2024-11-06 20:19 UTC, MikesGlitch commented on packages/loot-core/src/server/accounts/qif2json.ts
> +        throw new Error(t('Unknown Detail Code: {{code}}', { code: line[0] }));
No need to translate thrown errors (check rest of this file for the same issue)

2024-11-06 20:19 UTC, MikesGlitch commented on packages/loot-core/src/server/app.ts
> +        t('Conflicting method name, names must be globally unique: {name}', {
No need to translate thrown errors (check rest of this file for the same issue)

2024-11-06 20:19 UTC, MikesGlitch commented on packages/loot-core/src/server/aql/exec.ts
> +      throw new Error(t('Parameter {name} not provided to query', { name }));
No need to translate thrown errors (check rest of this file for the same issue)

2024-11-06 20:19 UTC, MikesGlitch commented on packages/loot-core/src/server/aql/schema/executors.ts
> +      t('Invalid “splits” option for transactions: “{{splitType}}”', {
No need to translate thrown errors (check rest of this file for the same issue)

2024-11-06 20:19 UTC, MikesGlitch commented on packages/desktop-client/src/components/rules/ActionExpression.tsx
> +      <Text>{t('to')}</Text>
Missing a space after _to_

2024-11-06 20:19 UTC, MikesGlitch commented on packages/desktop-client/src/components/rules/ActionExpression.tsx
> +          <Text>{t('template')}</Text>
Missing a space after _template_

2024-11-08 13:39 UTC, awaisalee commented
> This looks great! I've added some minor points about translating errors. Ideally we don't want to do that - those errors are for devs and for support - they shouldn't be shown to the user so shouldn't be translated.
> 
> E2E tests are failing as well - if you need help let us know.

Hi @MikesGlitch. I hope you're doing well. Thanks a lot for reviewing my PR. Following your suggestions, I removed the error translation code. I need some help with the "E2E Tests / Visual Regression" test. Could you either fix it or guide me on how to fix it?

2024-11-08 15:00 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Encryption.tsx
> +        <strong>{t('End-to-end encryption')}</strong>{' '}
This will be why the E2E tests are failing - You've duplicated the "End-to-end encryption" text. The other text needs translated too

2024-11-10 10:34 UTC, MikesGlitch requested changes

2024-11-10 10:34 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Themes.tsx
> +        {t(' change the user interface colors.')}
There's an extra space here - there's already on after _Themes_

2024-11-11 12:15 UTC, MikesGlitch requested changes

2024-11-11 12:15 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Encryption.tsx
> +        <strong>End-to-end Encryption is turned on.</strong>{' '}
```suggestion
```

2024-11-11 12:15 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Encryption.tsx
>          <strong>End-to-end encryption</strong> is not available when running
This text needs to be translated

2024-11-11 12:19 UTC, MikesGlitch requested changes

2024-11-11 12:19 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Encryption.tsx
>          without a server. Budget files are always kept unencrypted locally, and
This text should be translated

2024-11-11 12:57 UTC, MikesGlitch requested changes

2024-11-11 12:57 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Themes.tsx
> +        <strong> {t('Themes')} </strong>
```suggestion
        <strong>{t('Themes')} </strong>
```

2024-11-11 13:02 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Encryption.tsx
>          Your data is encrypted with a key that only you have before sending it
This still needs translated
![image](https://github.com/user-attachments/assets/5f3d80b9-f963-4125-89a9-27a770236b7f)

2024-11-11 13:43 UTC, awaisalee commented
@MikesGlitch Could you please guide me on how I checked the image?

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/cc5de1dd-a065-45f1-b014-6204a10426c2">

2024-11-11 13:58 UTC, MikesGlitch requested changes

2024-11-11 13:58 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Themes.tsx
> +        {t('change the user interface colors.')}
I think this is the last of it: 

```suggestion
        {t(' change the user interface colors.')}
```

2024-11-11 13:59 UTC, MikesGlitch commented
> @MikesGlitch Could you please guide me on how I view the image?

Go to the _Summary_ and download the artifact 
![image](https://github.com/user-attachments/assets/37fdb872-8d45-438b-a14c-db5584deeeec)

2024-11-11 14:18 UTC, MikesGlitch commented on packages/desktop-client/src/components/settings/Themes.tsx
> +        <strong>{t('Themes')} </strong>
```suggestion
        <strong>{t('Themes')}</strong>
```

2024-11-11 14:33 UTC, MikesGlitch approved these changes
Legend. Thanks for the work!

2024-11-11 14:37 UTC, merged