enhance: context menu budget page positioning
actualbudget/actual pull request #3775
Opened 2024-11-03 21:10 UTC by UnderKoen

fix: make popover non selectable

#3706

2024-11-03 21:24 UTC, UnderKoen commented on upcoming-release-notes/3775.md
> +And make popovers non selectable.
```suggestion
Position context menu's on the to budget page to the cursor, and make popovers non selectable.
```

2024-11-11 15:35 UTC, youngcw commented
Could you give some example repo steps?

2024-11-12 19:12 UTC, UnderKoen commented
@youngcw 
Sorry I hadn't change the description. 

For reproduction of the selectable context menu. I don't know how @jfdoming achieved this https://github.com/actualbudget/actual/pull/3381#pullrequestreview-2397604856

2024-11-12 21:22 UTC, jfdoming commented
> @youngcw Sorry I hadn't change the description.
> 
> For reproduction of the selectable context menu. I don't know how @jfdoming achieved this [#3381 (review)](https://github.com/actualbudget/actual/pull/3381#pullrequestreview-2397604856)

I believe I just hit Ctrl-A which selected the items

2024-11-19 09:19 UTC, matt-fidd requested changes
Just a spelling nit, then ready to merge

2024-11-19 09:19 UTC, matt-fidd commented on upcoming-release-notes/3775.md
> +Position context menu's on the to budget page to the cursor, and make popovers non selectable.
```suggestion
Position context menus on the to budget page to the cursor, and make popovers non selectable.
```

2024-11-26 21:07 UTC, UnderKoen commented on packages/desktop-client/src/hooks/useContextMenu.ts
> +  };
Popover does this for us

2024-11-26 21:08 UTC, UnderKoen commented on packages/desktop-client/src/components/transactions/TransactionsTable.jsx
> +      onContextMenu={handleContextMenu}
It does

2024-12-09 10:11 UTC, matt-fidd approved these changes
LGTM!

2024-12-09 10:14 UTC, matt-fidd requested changes
Ah sorry, couple of lint errors to fix first

2024-12-09 19:20 UTC, matt-fidd approved these changes

2024-12-09 19:32 UTC, merged