translation support for packages/loot-core/src/server/budget/template-nodes
actualbudget/actual pull request #3840
Opened 2024-11-15 12:04 UTC by AlexMuellr

translation support for `packages/loot-core/src/server/budget/template-nodes.ts`

2024-12-24 23:55 UTC, jfdoming commented on packages/loot-core/src/server/budget/template-notes.ts
> +        errors.push(t('{{id}}: Schedule {{template.name}} does not exist'));
@coderabbitai we use full strings as translation keys in this repository

2024-12-24 23:56 UTC, jfdoming commented
@AlexMuellr would love to merge this PR! Would you mind looking at the failing checks?

2025-01-17 12:11 UTC, matt-fidd commented on packages/loot-core/src/server/budget/template-notes.ts
> +import { useTranslation } from 'react-i18next';
We prefer `import { t } from 'i18next';` and then using `t(string)` in cases where react hooks can not be used.

2025-01-17 12:15 UTC, matt-fidd requested changes

2025-01-17 12:15 UTC, matt-fidd commented on packages/loot-core/src/server/budget/template-notes.ts
> +        errors.push(t('{{id}}: Schedule {{template.name}} does not exist'));
```suggestion
        errors.push(t('{{id}}: Schedule {{templateName}} does not exist', { id, templateName: template.name }));
```

2025-01-17 12:15 UTC, matt-fidd commented on packages/loot-core/src/server/budget/template-notes.ts
> +  const { t } = useTranslation();
This can't be used outside of a React component

```suggestion
```

2025-01-17 12:15 UTC, matt-fidd commented on packages/loot-core/src/server/budget/template-notes.ts
> +import { useTranslation } from 'react-i18next';
react-i18next doesn't work outside of React

```suggestion
import { t } from 'i18next';
```

2025-01-23 01:59 UTC, closed without merging