convert CategoryTransactions.jsx to .tsx
actualbudget/actual pull request #3875
Opened 2024-11-22 05:54 UTC by cindywu

2024-11-22 15:17 UTC, joel-jeremy requested changes

2024-11-22 15:17 UTC, joel-jeremy commented on packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
> +  category: CategoryEntity;
Please extract to a Props type

2024-11-22 15:17 UTC, joel-jeremy commented on packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
> +    (transaction: { id: string }) => {
This should be a `TransactionEntity`

2024-11-22 15:17 UTC, joel-jeremy commented on packages/desktop-client/src/components/mobile/budget/CategoryTransactions.tsx
> +        onRefresh
Maybe this should be nullable in `TransactionListWithBalances`

2024-11-23 04:37 UTC, cindywu commented
This is ready for review again!

2024-11-25 18:06 UTC, joel-jeremy requested changes

2024-11-25 18:06 UTC, joel-jeremy commented on packages/desktop-client/src/components/mobile/transactions/TransactionListWithBalances.jsx
> +  onRefresh = () => {},
This should be undefined as default because there's logic below which checks for this prop. Setting an empty function will introduce a regression.

2024-12-31 02:00 UTC, closed without merging