Convert SelectLinkedAccounts to TypeScript
actualbudget/actual pull request #3984
Opened 2024-12-14 23:17 UTC by dkhalife

2025-01-03 03:27 UTC, dkhalife commented on packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.tsx
> +  ] = useState(() => {
There are 2 types for Account, one is `NormalizedAccount` and another is `AccountEntity`

The `acc` here is an `AccountEntity` which has both an `id` and an `account_id`

My understanding is that the former refers to the Actual DB id for that account but the latter refers to the id the bank has given to that account, if this is a linked account. So with that said, I don't believe this suggestion is correct

2025-01-17 13:51 UTC, matt-fidd requested changes
A couple of comments, I'm not confident on all of them without some testing so feel free to tell me it won't work.

@joel-jeremy copying you in to have a look if you wouldn't mind, you're more up on your Typescript

2025-01-17 13:51 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.tsx
> +    localAccountId: string | undefined,
Could this be optional instead?

```suggestion
    localAccountId?: string,
```

2025-01-17 13:51 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.tsx
> +      if (localAccountId !== undefined) {
We use if(variable) for presence checks elsewhere in the code

```suggestion
      if (localAccountId) {
```

2025-01-17 13:51 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.tsx
> +              onSetLinkedAccount(externalAccount, undefined);
With the other change to make the second argument optional
```suggestion
              onSetLinkedAccount(externalAccount);
```

2025-01-17 13:51 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.tsx
> +    const chosenLocalAccountIds: string[] = Object.values(chosenAccounts);
Can you type this using AccountEntity?

```suggestion
    const chosenLocalAccountIds: AccountEntity['id'][] = Object.values(chosenAccounts);
```

2025-01-17 13:51 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/SelectLinkedAccountsModal.tsx
> +type LinkedAccountIds = { [key: string]: string };
Can this be done with AccountEntity instead of string?

2025-01-17 13:51 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/CreateAccountModal.tsx
> +};
Can this use types from AccountEntity?

2025-02-19 05:15 UTC, closed without merging

2025-02-19 05:16 UTC, dkhalife commented
Closing this one as it got stale and I currently don't have bandwidth to move forward with it