Initial upgrade to redux toolkit
actualbudget/actual pull request #4000
Opened 2024-12-17 23:14 UTC by joel-jeremy

Initial migration to redux-toolkit. This PR focuses on retrofitting the existing reducers to the newer redux toolkit APIs. We can work on converting them to redux slices in a future PR. 

Aside from converting to the usage of typed `useAppDispatcher` and `useAppSelector`, I had to do some changes to the `SET_LAST_UNDO_STATE` and `SET_LAST_SPLIT_STATE` to prevent mutating the state in their reducers because redux toolkit now check for that.

There are still some redux validation errors due to non-serializable values being on the the state e.g. modal callback functions. But I have disabled those checks temporarily until we can address them in a future PR.

- [x] Use redux toolkit's `configureStore` API
- [x] Address Redux [Immutability Middleware](https://redux-toolkit.js.org/api/immutabilityMiddleware) errors in reducers (`SET_LAST_UNDO_STATE`, `SET_LAST_SPLIT_STATE`)
- [ ] Address Redux [Serializability Middleware](https://redux-toolkit.js.org/api/serializabilityMiddleware) errors in reducers (e.g. modal callback functions)
- [ ] Update reducers to use new redux toolkit `createSlice` API
- [ ] Update actions to use new redux toolkit `createAction` API

2024-12-17 23:50 UTC, joel-jeremy commented
/update-vrt

2024-12-30 22:07 UTC, jfdoming requested changes
Thanks for doing this! Left one quick suggestion to start since I think it will make the diff much more manageable to review 😅

2024-12-30 22:07 UTC, jfdoming commented on packages/desktop-client/src/redux/index.ts
> +export const useAppSelector = useSelector.withTypes<RootState>();
Is it possible to keep the names the same so we don't have to rename everywhere?

```suggestion
import { useDispatch as useReduxDispatch, useSelector as useReduxSelector } from 'react-redux';

import { type AppDispatch, type RootState } from 'loot-core/client/store';

export const useDispatch = useReduxDispatch.withTypes<AppDispatch>();
export const useSelector = useReduxSelector.withTypes<RootState>();
```

2025-01-02 07:43 UTC, jfdoming requested changes
Thanks for the changes! Code looks mostly good now, had some questions around performance and bug bashing

2025-01-02 07:43 UTC, jfdoming commented on packages/desktop-client/src/hooks/useSplitsExpanded.tsx
> +        const idSet = new Set(data.state.ids);
Or, since we're not even using Redux at all anymore for this state, couldn't we just keep using a `Set`? Or is the plan to later move this to Redux?

2025-01-02 07:43 UTC, jfdoming commented on packages/loot-core/src/platform/client/undo/index.d.ts
> +  current: unknown;
Instead of typing as `unknown`, does it work to type it like this and avoid some type casts?

```typescript
type CurrentUndoState {
  id?: string;
  url: unknown;
  openModal: ModalType;
  selectedItems: {
    name: string;
    items: Set<string>;
  } | null;
}

export type UndoState = CurrentUndoState & {
  current: CurrentUndoState | null;
}
```

2025-01-02 07:43 UTC, jfdoming commented on packages/desktop-client/src/components/payees/ManagePayeesWithData.tsx
> +      undo.setUndoState('current', null);
One side-effect of this approach is that other components (and this component) won't rerender when the undo state changes. Not sure if/where this matters—have you had a chance to confirm if any undo behaviour is broken? Wasn't able to repro anything in my testing

2025-01-02 07:43 UTC, jfdoming commented on packages/desktop-client/src/components/table.tsx
> +    modalStackLength.current = modalState.modalStack.length;
Unfortunately I think this approach breaks the field refocus behaviour due to caching. Steps to repro:
1. Mark transactions as reconciled
2. Edit the payee on a reconciled transaction
3. Hit 'Cancel' on the modal
On edge, this refocuses the payee field. However in this PR the field is not focused

2025-01-02 07:43 UTC, jfdoming commented on .eslintrc.js
> +                message: 'Please use Actual’s useDispatch() hook instead.',
nit: maybe we should specify where to find Actual's hook? e.g. 
```suggestion
                message: 'Please import useDispatch() from `src/redux` instead.',
```

2025-01-06 16:56 UTC, joel-jeremy commented on packages/desktop-client/src/hooks/useSplitsExpanded.tsx
> +        const idSet = new Set(data.state.ids);
Nice catch! Reverted it back to a Set

2025-01-06 16:57 UTC, joel-jeremy commented on packages/desktop-client/src/components/table.tsx
> +    modalStackLength.current = modalState.modalStack.length;
Should be fixed on the latest push

2025-01-06 18:07 UTC, joel-jeremy commented on packages/desktop-client/src/redux/index.ts
> +export const useAppSelector = useSelector.withTypes<RootState>();
I have reverted these renames. These are based on redux toolkit recommendations https://redux.js.org/usage/usage-with-typescript. Will separate them out on another PR instead to make this PR more manageable to review.

2025-01-06 18:21 UTC, joel-jeremy commented on packages/loot-core/src/client/store/index.ts
> +export type GetRootState = typeof store.getState;
Rename PR: https://github.com/actualbudget/actual/pull/4101

2025-01-07 00:59 UTC, jfdoming submitted a review, later dismissed
Looks good now! Pending the release which has not yet gone through the MS store 😬

2025-01-07 00:59 UTC, jfdoming commented on packages/desktop-client/src/components/table.tsx
> +  const modalStackLength = useRef(modalState.modalStack.length);
If we're not using a `useEffect` couldn't this just be a normal variable instead of a ref?

2025-01-07 03:52 UTC, joel-jeremy commented on packages/desktop-client/src/components/table.tsx
> +  const modalStackLength = useRef(modalState.modalStack.length);
It's still needed since we only want the initial modal stack length and not get the updated length on re-renders

2025-01-07 14:20 UTC, jfdoming submitted a review, later dismissed

2025-01-08 00:34 UTC, merged