Pluggy.ai bank sync
actualbudget/actual pull request #4049
Opened 2024-12-27 17:34 UTC by lelemm

Pluggy.ai bank sync for Brazilian banks

2024-12-27 18:11 UTC, lelemm commented
@coderabbitai review

2025-01-23 02:56 UTC, lelemm commented
/update-vrt

2025-01-23 03:08 UTC, lelemm commented
/update-vrt

2025-01-23 16:34 UTC, lelemm commented
@matt-fidd this is marked as stale but it just need review

2025-01-23 16:37 UTC, matt-fidd commented
No worries, I think I was waiting for the server one to be marked RFR before I did them both at the same time.
I'll take a look during the freeze so it will have a good stretch in edge before it goes out

2025-01-23 16:51 UTC, lelemm commented
> No worries, I think I was waiting for the server one to be marked RFR before I did them both at the same time. I'll take a look during the freeze so it will have a good stretch in edge before it goes out

there are instructions on the bank sync channel (here: [Sandbox](https://discord.com/channels/937901803608096828/1323118989429309591/1323384307624181811) ) so you can test with transactions. Docs for the sandbox [here](https://docs.pluggy.ai/docs/sandbox)

2025-01-27 17:26 UTC, matt-fidd requested changes
A few minor comments

2025-01-27 17:26 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/CreateAccountModal.tsx
> +        title: 'Error when trying to contact Pluggy.ai',
Missed translation

2025-01-27 17:26 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/CreateAccountModal.tsx
> +                            )}
This is difficult to translate as it'll generate 4 separate strings with no context. We prefer using `<Trans>` components where possible and wrapping the entire translatable string. This, for example, would be:

```suggestion
                            <Trans>
                              <strong>
                                Link a <em>Brazilian</em> bank account
                              </strong>{' '}
                              to automatically download transactions.
                              Pluggy.ai provides reliable, up-to-date information from hundreds of banks.
                            </Trans>
```

2025-01-27 17:26 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/PluggyAiInitialiseModal.tsx
> +            </Text>
Same here, one `<Trans>` component wrapping would be better.

2025-01-27 17:26 UTC, matt-fidd commented on packages/loot-core/src/server/accounts/sync.ts
> +  to: string,
Does this need a "to" date? Can we not just take anything that pluggy sends back?

2025-01-27 17:26 UTC, matt-fidd commented on packages/loot-core/src/server/main.ts
> +    name: externalAccount.institution ?? 'Unknown',
'Unknown' should be marked for translation

2025-01-27 17:26 UTC, matt-fidd commented on packages/loot-core/src/server/main.ts
> +    ]);
This one's optional but using AQL instead would be good

2025-02-21 02:02 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +      );
This is a problem in other places too, I'll clean up the bank sync stuff in another PR

2025-02-21 02:12 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +      );
I guess using the node library from pluggy already solves this

2025-02-26 16:25 UTC, lelemm commented on packages/desktop-client/src/components/modals/PluggyAiInitialiseModal.tsx
> +            </Text>
done

2025-02-26 16:25 UTC, lelemm commented on packages/loot-core/src/server/accounts/sync.ts
> +  to: string,
removed `to`

2025-02-26 16:25 UTC, lelemm commented on packages/loot-core/src/server/main.ts
> +    name: externalAccount.institution ?? 'Unknown',
done

2025-02-26 16:25 UTC, lelemm commented on packages/loot-core/src/server/main.ts
> +    ]);
I kept the original sql to be consistent between the other bank syncs

2025-02-26 18:21 UTC, lelemm commented on packages/sync-server/upcoming-release-notes/530.md
done

2025-02-27 00:54 UTC, matt-fidd requested changes
Sorry for all of the comments, if I'm wrong about any then please call me out!

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        }
```suggestion
        newTrans.booked = !(trans.status === 'PENDING')
```

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        dateToUse = trans.date;
I don't think we need the `dateToUse` stuff (is it copied from SimpleFIN?) Can we just set `transactionDate = new Date(trans.date)`?

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        }
Could we extract this out into its own function?

I think it can be simplified to

```js
const getPayeeName = (trans): string => {
  if (trans.merchant) {
    return trans.merchant.name || trans.merchant.businessName || '';
  }

  if (trans.paymentData) {
    const { receiver, payer } = trans.paymentData;

    if (trans.type === 'DEBIT' && receiver) {
      return receiver.name || receiver.documentNumber?.value || '';
    }

    if (trans.type === 'CREDIT' && payer) {
      return payer.name || payer.documentNumber?.value || '';
    }
  }

  return '';
};
```

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        newTrans.valueDate = newTrans.bookingDate; //always undefined?
This isn't required anymore, you can just send `trans.date`

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        newTrans.remittanceInformationUnstructured = trans.descriptionRaw;
```suggestion
        newTrans.notes = trans.descriptionRaw;
```

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      ];
I can't actually see where these are used in the frontend code, I don't think we need two of them either way! Can we keep just the 'expected' please? I know this is copied from SimpleFin but I've got a feeling it's not required there either.

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      }
Could we move this into the service logic? I think `getTransactionsByAccountId` should always return all available if possible.

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +          transactions: { all, booked, pending },
These need to be sorted, see https://github.com/actualbudget/actual/pull/4354 for how I implemented for SimpleFIN

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      }
Is this duplicated with https://github.com/actualbudget/actual/blob/94f94497af17112886cddab49690219ae6a580e6/packages/loot-core/src/server/accounts/sync.ts#L58-L67 ?

For reference, I think we should be doing this on the server, not in the client, but we should stick with the framework for this change.

Maybe we can add `.toLowerCase()` to the function above and remove this bit for now?

2025-02-27 00:54 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      }
It would be nice to return all of the transaction properties here so that the custom mapping in the new bank sync page has something to look at.

```suggestion
        const finalTrans = { ...trans, ...newTrans };
        if (newTrans.booked) {
          booked.push(finalTrans);
        } else {
          pending.push(finalTrans);
        }
        all.push(finalTrans);
      }
```

2025-02-27 00:54 UTC, matt-fidd commented on packages/desktop-client/src/components/modals/PluggyAiInitialiseModal.tsx
> +              {t('Save and continue')}
```suggestion
              <Trans>Save and continue</Trans>
```

2025-02-27 00:56 UTC, matt-fidd commented
Oh, could you have a look at https://github.com/actualbudget/actual/blob/94f94497af17112886cddab49690219ae6a580e6/packages/desktop-client/src/components/banksync/EditSyncAccount.tsx#L43-L78 and see if there are any extra fields we can expose for pluggy as well please?

2025-02-27 01:04 UTC, matt-fidd commented
Can you also add pluggy as to the BankSyncProviders type and to the readable version on the bank sync page?

```patch
diff --git a/packages/desktop-client/src/components/banksync/index.tsx b/packages/desktop-client/src/components/banksync/index.tsx
index 4526920c..021bca87 100644
--- a/packages/desktop-client/src/components/banksync/index.tsx
+++ b/packages/desktop-client/src/components/banksync/index.tsx
@@ -28,6 +28,7 @@ const useSyncSourceReadable = () => {
   const syncSourceReadable: Record<SyncProviders, string> = {
     goCardless: 'GoCardless',
     simpleFin: 'SimpleFIN',
+    pluggyai: 'Pluggy.ai',
     unlinked: t('Unlinked'),
   };

diff --git a/packages/loot-core/src/types/models/bank-sync.d.ts b/packages/loot-core/src/types/models/bank-sync.d.ts
index f0ab8a37..789c9c57 100644
--- a/packages/loot-core/src/types/models/bank-sync.d.ts
+++ b/packages/loot-core/src/types/models/bank-sync.d.ts
@@ -20,4 +20,4 @@ export type BankSyncResponse = {
   error_code: string;
 };

-export type BankSyncProviders = 'goCardless' | 'simpleFin';
+export type BankSyncProviders = 'goCardless' | 'simpleFin' | 'pluggyai';
```

2025-02-27 01:18 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      }
Looks like the service could use `pluggy.fetchAllTransactions` instead

https://github.com/pluggyai/pluggy-node/blob/36c37e4524084c3e7e52203fb638079bdad88345/src/client.ts#L177C9-L177C29

2025-02-27 17:23 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      }
I guess the intent is the same...

This logic you marked is used just by gocardless, should we use this logic for all bank syncs?
pluggy supports two types of accounts: `BANK` and `CREDIT`

2025-02-27 17:25 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      }
Oh my bad, I read it as being used for all. Keep this in here for now then and I'll tidy up GoCardless another time.

2025-02-27 17:50 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        dateToUse = trans.date;
sure

2025-02-27 17:50 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        }
done

2025-02-27 17:51 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        }
added to `pluggyai-service.js`

2025-02-27 17:51 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      ];
Tried to find where its used and I couldn't find any, removed second

2025-02-27 17:52 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      }
moved as `getTransactions`

2025-02-27 17:52 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +      }
done

2025-02-27 17:53 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +          transactions: { all, booked, pending },
done

2025-02-27 17:53 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        newTrans.remittanceInformationUnstructured = trans.descriptionRaw;
done, also changed to 
`newTrans.notes = trans.descriptionRaw || trans.description;`

2025-02-27 18:08 UTC, lelemm commented
@matt-fidd I'm flattering the original trans so its easier to use in the bank sync page.

this is a example of a real transaction:
```json
{
  id: "95798789-ab8b-490a-b4fe-2529ee7cf99a",
  description: "[redacted]",
  descriptionRaw: "[redacted]",
  currencyCode: "BRL",
  amount: -1000,
  amountInAccountCurrency: null,
  category: "Taxes",
  categoryId: "15000000",
  balance: null,
  accountId: "[redacted]",
  providerCode: null,
  status: "POSTED",
  "paymentData.payer.accountNumber": null,
  "paymentData.payer.branchNumber": null,
  "paymentData.payer.documentNumber.type": "CPF",
  "paymentData.payer.documentNumber.value": "[redacted]",
  "paymentData.payer.name": null,
  "paymentData.payer.routingNumber": null,
  "paymentData.payer.routingNumberISPB": null,
  "paymentData.paymentMethod": "OTHER",
  "paymentData.reason": null,
  "paymentData.receiver.accountNumber": null,
  "paymentData.receiver.branchNumber": null,
  "paymentData.receiver.documentNumber.type": "CNPJ",
  "paymentData.receiver.documentNumber.value": "[redacted]",
  "paymentData.receiver.name": "[redacted]",
  "paymentData.receiver.routingNumber": null,
  "paymentData.receiver.routingNumberISPB": null,
  "paymentData.receiverReferenceId": null,
  "paymentData.referenceNumber": null,
  "paymentData.boletoMetadata": null,
  type: "DEBIT",
  operationType: "[redacted]",
  creditCardMetadata: null,
  acquirerData: null,
  merchant: null,
  booked: true,
  date: "2025-02-26",
  payeeName: "[redacted]",
  notes: "[redacted]",
  transactionAmount: {
    amount: -1000,
    currency: "BRL",
  },
  transactionId: "95798789-ab8b-490a-b4fe-2529ee7cf99a",
  valueDate: "2025-02-26T02:34:07.939Z",
  sortOrder: "2025-02-26T02:34:07.939Z",
}
```

2025-02-27 18:11 UTC, matt-fidd commented
> @matt-fidd I'm flattering the original trans so its easier to use in the bank sync page.
> 
> this is a example of a real transaction:
> ...

I don't think that'll match the way other providers work. Could you filter out the nulls to make it smaller?

2025-02-27 18:15 UTC, lelemm commented
> > @matt-fidd I'm flattering the original trans so its easier to use in the bank sync page.
> > this is a example of a real transaction:
> > ...
> 
> I don't think that'll match the way other providers work. Could you filter out the nulls to make it smaller?

sure, this would be a filtered out transaction:

```json
{
  id: "95798789-ab8b-490a-b4fe-2529ee7cf99a",
  description: "[redacted]",
  descriptionRaw: "[redacted]",
  currencyCode: "BRL",
  amount: -22222,
  category: "Taxes",
  categoryId: "15000000",
  accountId: "b3f58318-3f81-408b-9bd5-729cb329fdd2",
  status: "POSTED",
  "paymentData.payer.documentNumber.type": "CPF",
  "paymentData.payer.documentNumber.value": "[redacted]",
  "paymentData.paymentMethod": "OTHER",
  "paymentData.receiver.documentNumber.type": "CNPJ",
  "paymentData.receiver.documentNumber.value": "[redacted]",
  "paymentData.receiver.name": "[redacted]",
  type: "DEBIT",
  operationType: "[redacted]",
  booked: true,
  date: "2025-02-26",
  payeeName: "[redacted]",
  notes: "[redacted]",
  transactionAmount: {
    amount: -2222,
    currency: "BRL",
  },
  transactionId: "95798789-ab8b-490a-b4fe-2529ee7cf99a",
  valueDate: "2025-02-26T02:34:07.939Z",
  sortOrder: "2025-02-26T02:34:07.939Z",
}
```

2025-02-27 18:20 UTC, matt-fidd commented
> > > @matt-fidd I'm flattering the original trans so its easier to use in the bank sync page.
> > > this is a example of a real transaction:
> > > ...
> > 
> > 
> > I don't think that'll match the way other providers work. Could you filter out the nulls to make it smaller?
> 
> sure, this would be a filtered out transaction:
> 
> ```json
> {
>    "id":"95798789-ab8b-490a-b4fe-2529ee7cf99a",
>    "description":"[redacted]",
>    "descriptionRaw":"[redacted]",
>    "currencyCode":"BRL",
>    "amount":-22222,
>    "category":"Taxes",
>    "categoryId":"15000000",
>    "accountId":"b3f58318-3f81-408b-9bd5-729cb329fdd2",
>    "status":"POSTED",
>    "paymentData.payer.documentNumber.type":"CPF",
>    "paymentData.payer.documentNumber.value":"[redacted]",
>    "paymentData.paymentMethod":"OTHER",
>    "paymentData.receiver.documentNumber.type":"CNPJ",
>    "paymentData.receiver.documentNumber.value":"[redacted]",
>    "paymentData.receiver.name":"[redacted]",
>    "type":"DEBIT",
>    "operationType":"[redacted]",
>    "booked":true,
>    "date":"2025-02-26",
>    "payeeName":"[redacted]",
>    "notes":"[redacted]",
>    "transactionAmount":{
>       "amount":-2222,
>       "currency":"BRL"
>    },
>    "transactionId":"95798789-ab8b-490a-b4fe-2529ee7cf99a",
>    "valueDate":"2025-02-26T02:34:07.939Z",
>    "sortOrder":"2025-02-26T02:34:07.939Z"
> }
> ```

LGTM! I don't know what we should expose in the mappings. Maybe description, rawDescription and them some of the paymentData stuff?

2025-02-27 18:24 UTC, lelemm commented
> ```json
> category
> ```

```diff
diff --git a/packages/desktop-client/src/components/banksync/EditSyncAccount.tsx b/packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
index b13efd362..3b0b61b02 100644
--- a/packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
+++ b/packages/desktop-client/src/components/banksync/EditSyncAccount.tsx
@@ -62,6 +62,15 @@ const mappableFields: MappableField[] = [
       'remittanceInformationStructured',
       'remittanceInformationStructuredArrayString',
       'additionalInformation',
+      'paymentData.payer.accountNumber',
+      'paymentData.payer.documentNumber.value',
+      'paymentData.payer.name',
+      'paymentData.receiver.accountNumber',
+      'paymentData.receiver.documentNumber.value',
+      'paymentData.receiver.name',
+      'merchant.name',
+      'merchant.businessName',
+      'merchant.cnpj',
     ],
   },
   {
@@ -73,6 +82,16 @@ const mappableFields: MappableField[] = [
       'remittanceInformationStructured',
       'remittanceInformationStructuredArrayString',
       'additionalInformation',
+      'category',
+      'paymentData.payer.accountNumber',
+      'paymentData.payer.documentNumber.value',
+      'paymentData.payer.name',
+      'paymentData.receiver.accountNumber',
+      'paymentData.receiver.documentNumber.value',
+      'paymentData.receiver.name',
+      'merchant.name',
+      'merchant.businessName',
+      'merchant.cnpj',
     ],
   },
 ];

```

2025-02-27 18:28 UTC, matt-fidd commented
Once you're finalised and pushed I'll pull down all of the changes and give it a go.

2025-02-27 20:35 UTC, matt-fidd reviewed
Not sure if it's just the sandbox data, but `paymentData.receiver.documentNumber.value` doesn't seem to have a useful value for the payeeName.

`paymentData.receiver.documentNumber.value: "11265173793"`

<img width="837" alt="image" src="https://github.com/user-attachments/assets/e17f2e60-83ed-4ba8-b8cd-a2afddf5c558" />

2025-02-27 20:35 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +      newTrans.valueDate = trans.date;
This can be removed as we're using `trans.date`

2025-02-27 20:35 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +    const allSorted = all.sort(sortFunction);
Can the processing be moved back to the app file? Sorry if I confused you, the pagination code should be in the service but normalising them should be in the app.

2025-02-27 21:37 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +    const allSorted = all.sort(sortFunction);
ohh, got it. I will do it

2025-02-27 21:39 UTC, lelemm commented
> Not sure if it's just the sandbox data, but `paymentData.receiver.documentNumber.value` doesn't seem to have a useful value for the payeeName.
> 
> `paymentData.receiver.documentNumber.value: "11265173793"`
> 
the documentnumber is the social security number for persons and the for companies Company Registration Number

2025-02-27 21:45 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +      newTrans.valueDate = trans.date;
the documentnumber is the social security number for persons and the for companies Company Registration Number, If the bank doesn't provide the name, it may provide the document number. it depends on each bank

2025-02-27 21:54 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +    const allSorted = all.sort(sortFunction);
done

2025-02-27 21:58 UTC, matt-fidd requested changes
Last two comments, I promise!

2025-02-27 21:58 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/app-pluggyai.js
> +        newTrans.sortOrder = trans.date;
```suggestion
        newTrans.sortOrder = transactionDate.getTime();
```

2025-02-27 21:58 UTC, matt-fidd commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +  },
can this go into the app as well?

2025-02-27 22:00 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +  },
sure

2025-02-27 22:07 UTC, lelemm commented on packages/sync-server/src/app-pluggyai/pluggyai-service.js
> +  },
done

2025-02-27 22:10 UTC, matt-fidd approved these changes
Great work, thank you! This'll be a big one in v25.4 😁

2025-02-27 22:11 UTC, lelemm commented
> Great work, thank you! This'll be a big one in v25.4 😁

I can get rid of my docker image \o/

2025-03-04 09:58 UTC, matt-fidd commented
@lelemm ready to get this in? :)

2025-03-04 11:07 UTC, merged

2025-05-15 15:35 UTC, igorcmoura commented
Thank you for implementing this! I was looking forward for being able to import from Brazilian banks.

So, I'm testing this feature and the docs states "Data refresh frequency may vary by financial institution.". However, my accounts don't seem to have updated since I created this integration 2 weeks ago. Also there is no info about the last sync:
![image](https://github.com/user-attachments/assets/229d3d50-f80e-4a0a-aa24-4a6d93bc4e70)

Is there something I'm missing?

2025-05-15 15:38 UTC, youngcw commented
> Thank you for implementing this! I was looking forward for being able to import from Brazilian banks.
> 
> So, I'm testing this feature and the docs states "Data refresh frequency may vary by financial institution.". However, my accounts don't seem to have updated since I created this integration 2 weeks ago. Also there is no info about the last sync: ![image](https://private-user-images.githubusercontent.com/8890509/444188912-229d3d50-f80e-4a0a-aa24-4a6d93bc4e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDczMjM3NzgsIm5iZiI6MTc0NzMyMzQ3OCwicGF0aCI6Ii84ODkwNTA5LzQ0NDE4ODkxMi0yMjlkM2Q1MC1mODBlLTRhMGEtYWEyNC00YTZkOTNiYzRlNzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MTVUMTUzNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFmMzUwYmEwNTg4Y2I4MmEyYWM1MjliMzEzYTY3YTdkZTU3MDYxYWM5ZjU2NTI5YzUyMmVmNGFiNjRkMGRkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.H_LzghxbZxfZkBz8mvzlCqALRGNG-fDLMDjVrvZ24Us)
> 
> Should it take this long for a refresh? Or is there something I'm missing?

are you clicking "bank sync" in your accounts?

2025-05-15 15:43 UTC, igorcmoura commented
> are you clicking "bank sync" in your accounts?

Yes, I enabled bank sync for all these accouts, if that's what you mean. Or is there a button to force sync it?
It imported fine as soon as I enabled it, but it has not updated since.

2025-05-15 15:44 UTC, youngcw commented
> > are you clicking "bank sync" in your accounts?
> 
> Yes, I enabled bank sync for all these accounts, if that's what you mean. Or is there a button to force sync it? It imported fine as soon as I enabled it, but it has not updated since.

there is a button in the account page you need to click for it to sync.  Thats why you don't have any last sync values, you haven't synced since setup

2025-05-15 15:46 UTC, igorcmoura commented
I'm really sorry, I just found that Bank Sync button 🙃 I swear I looked for it but didn't look at the right place.
It worked! Thank you so much! And sorry for the inconvenience

2025-06-17 17:48 UTC, AugustoPinheiro commented
@BrunoPradoBR  If you want to test it, I had the same problem here, I went up to my server and opened a PR, I'm open to improvements #5184

2025-08-29 11:47 UTC, davisonpc commented
I'm facing a loop error in connection. It's everything ok at pluggy.ai, but it's not possible to sync. I thought it was wrong and redefined everything at pluggy and the error persists. 

The error: I configure the ID, the secret, the items IDs and when try to connect an account the system ask me again to typing the credentials.

I thought it was an MeuPluggy error and i've created a direct connection but the error persists.

I tried creating a new AB file and the error persists.



<img width="681" height="656" alt="image" src="https://github.com/user-attachments/assets/a6f1c1a3-323a-44e5-bdef-df061aef4ad2" />
<img width="661" height="111" alt="image" src="https://github.com/user-attachments/assets/62bd80d7-a492-43cc-a47e-13ce06400a2e" />
<img width="1542" height="79" alt="image" src="https://github.com/user-attachments/assets/95ec2992-9997-4822-909e-b1230e9d03ab" />
<img width="1607" height="77" alt="image" src="https://github.com/user-attachments/assets/da303188-58bf-4371-af77-b8351c24807f" />
<img width="600" height="385" alt="image" src="https://github.com/user-attachments/assets/f6fa1ca9-9b84-4f9a-8752-626e1dfc3e08" />
<img width="567" height="433" alt="image" src="https://github.com/user-attachments/assets/ca4d62ca-90d2-498a-b296-caf92d488196" />