(typescript) Refactoring the mobile TransactionList component to typescript
actualbudget/actual pull request #4063
Opened 2024-12-31 20:38 UTC by leoltl

Refactoring the mobile TransactionList component to typescript.

re: #1483

2024-12-31 20:55 UTC, leoltl commented on packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
> +  isNewTransaction?: (transaction: TransactionEntity['id']) => boolean;
I don't see this prop being used anywhere, I am not sure if I should delete it or leave that as an optional

2024-12-31 20:59 UTC, leoltl commented on packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
> +              })}
The menu in L348 does not have a `delete` `MenuItem`, and typescript was complaining it referencing a value which it has no overlap.
![image](https://github.com/user-attachments/assets/ec53e1f7-6ebd-4afd-9922-79794ef70e8a)
So I am extracting that conditional out as an inline function.

2025-01-06 18:45 UTC, joel-jeremy requested changes

2025-01-06 18:45 UTC, joel-jeremy commented on packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
> +  style?: Parameters<typeof FloatingActionBar>[0]['style'];
```suggestion
  style?: CSSProperties;
```

2025-01-06 18:45 UTC, joel-jeremy commented on packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
> +              })}
Would the typescript error be fixed if we explicitly type the item parameter on L348 or type the `getMenuItemStyle` function?

2025-01-06 18:45 UTC, joel-jeremy commented on packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
> +  isNewTransaction?: (transaction: TransactionEntity['id']) => boolean;
If not used then we can just delete it

2025-01-06 19:50 UTC, leoltl reviewed
@joel-jeremy Thanks for reviewing the PR. I have updated my PR to address the few comments

2025-01-06 19:50 UTC, leoltl commented on packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
> +  style?: Parameters<typeof FloatingActionBar>[0]['style'];
Addressed: [56eba2e](https://github.com/actualbudget/actual/pull/4063/commits/56eba2e1d1a7bc8efffe9e9517cc135fa0ea0e32)

2025-01-06 19:50 UTC, leoltl commented on packages/desktop-client/src/components/mobile/transactions/TransactionListItem.tsx
> +  isNewTransaction?: (transaction: TransactionEntity['id']) => boolean;
Deleted: [56eba2e](https://github.com/actualbudget/actual/pull/4063/commits/56eba2e1d1a7bc8efffe9e9517cc135fa0ea0e32)

2025-01-06 19:50 UTC, leoltl commented on packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
> +              })}
I have typed the `getMenuItemStyle` function and seem to made typescript happy
[5623c21](https://github.com/actualbudget/actual/pull/4063/commits/5623c2151b4b556ec7d5c67477e25b3d3456c1a7)

2025-01-06 21:15 UTC, joel-jeremy commented on packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
>    const getMenuItemStyle = useCallback(
I think this would also work instead of exporting the type
```suggestion
  const getMenuItemStyle: ComponentProps<typeof Menu>['getItemStyle'] = useCallback(
```

2025-01-08 06:02 UTC, leoltl commented on packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
>    const getMenuItemStyle = useCallback(
@joel-jeremy Thanks for the second review and suggestion! Unfortunately the proposed change doesn't seem to work. 😢 
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/a67ea185-979d-4ad5-bff4-28cb9958ea3c" />

I believe it is because the type of `'NameType'` in the first argument of the Menu's `'getItemStyle'` is a generic that bounds to the actual `Menu` instance (i.e. TS resolving the type from the `items` the `Menu` instance was passed). Whereas it is `unknown` type when it is not bounded to the `Menu` instance. 

I am open to other suggestion, but so far setting this anonymous function with generic type is only way I get typing to work.

2025-01-08 06:32 UTC, leoltl commented on packages/desktop-client/src/components/mobile/transactions/TransactionList.tsx
> +                          accountsById[String(value)]?.name ?? value;
updated: c06df652dbfb813f0a596cb5b78ea6f672d4099d

2025-01-16 22:37 UTC, joel-jeremy approved these changes
LGTM!

2025-01-16 22:38 UTC, merged