:bug: (autocomplete) consistent input height between multi/single input
actualbudget/actual pull request #787
Opened 2023-03-18 19:18 UTC by MatissJanis

Making consistent height between multi/single input autocomplete.

Before:
<img width="333" alt="Screenshot 2023-03-18 at 19 18 14" src="https://user-images.githubusercontent.com/886567/226132111-21aae538-f42f-43be-8281-93283ed77ec1.png">

After:
<img width="321" alt="Screenshot 2023-03-18 at 19 17 21" src="https://user-images.githubusercontent.com/886567/226131970-df46e053-6794-48e6-a68f-99c66cce6551.png">
<img width="325" alt="Screenshot 2023-03-18 at 19 17 15" src="https://user-images.githubusercontent.com/886567/226131982-a449aee7-70d6-4445-a5b2-a4a476ee10ba.png">

2023-03-18 20:32 UTC, j-f1 requested changes
Now they overlap when wrapping onto multiple lines:

<img width="320" alt="Screenshot_2023-03-18 16 32 04" src="https://user-images.githubusercontent.com/25517624/226137042-ab55eede-9979-4ae5-8842-59ec87e7a382.png">

2023-03-18 20:44 UTC, MatissJanis commented
Good spot @j-f1 ! Fixed: https://github.com/actualbudget/actual/pull/787/commits/2b9f67e32ba46b0985ad9ea794865ece308c9024

2023-03-18 21:08 UTC, j-f1 approved these changes
LGTM! One more very small nit: there’s 2px of extra padding on the horizontal axis — maybe remove the left margin on the tokens?

<img width="848" alt="Screenshot_2023-03-18 17 07 39" src="https://user-images.githubusercontent.com/25517624/226140195-11c0e828-1af6-42b0-aa38-1c54d3287176.png">

2023-03-19 17:19 UTC, MatissJanis commented
> LGTM! One more very small nit: there’s 2px of extra padding on the horizontal axis — maybe remove the left margin on the tokens?
> 
> <img alt="Screenshot_2023-03-18 17 07 39" width="848" src="https://user-images.githubusercontent.com/25517624/226140195-11c0e828-1af6-42b0-aa38-1c54d3287176.png">

I think it's better to keep this padding in order to have both X and Y paddings consistent.
<img width="323" alt="Screenshot 2023-03-19 at 17 19 09" src="https://user-images.githubusercontent.com/886567/226194832-4eb5f096-594e-4f6d-90bc-035c44aa31e5.png">

2023-03-19 17:20 UTC, merged

2023-03-19 19:59 UTC, j-f1 commented
They don’t seem to line up exactly. Will open a PR to fix!

<img width="328" alt="Screenshot_2023-03-19 15 58 41" src="https://user-images.githubusercontent.com/25517624/226205669-b7479e67-7ee5-477f-a79e-8cfbde79715c.png">

2023-03-19 20:01 UTC, MatissJanis commented
Ohhh, the difference between 5 and 3? Ok, I see what you mean.

I thought you meant to reduce the horizontal spacing between pills (4), but not vertical.